name: Docker CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # STEP 1: Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v3

    # STEP 2: Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # STEP 3: Build Docker Image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest .

    # STEP 4: Push Docker Image to Docker Hub
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest

    # STEP 5: Deploy on EC2
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSHKEY }}
        script: |
          cd /home/ubuntu
          sudo bash deplo.sh
